### ISSUE TITLE
Clean - Create Task

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#104]
1. Review #9    again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task - it is for masters, but many things will be applicable to this page as well.
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by prupapara** [comment]
Done Please verify.

**Comment by AAndharia** [comment]
not looked too much in this task yet, but none of the select query should load extra fields from database, for example : CreatedOn, UpdatedOn.

**Comment by prupapara** [comment]
Done Please verify.

**Comment by jmervana** [comment]
@prupapara 
Give proper comments to service method
Add TaskMgmtService.cs to iocconfig

**Comment by prupapara** [comment]
Done Please verify.
I have remove unused method in service.

**Comment by jmervana** [comment]
@AAndharia 
I have tested and works fine
