### ISSUE TITLE
All CRUD > xEditable textbox size as well  as given textbox 

### ISSUE THREAD

**Issue by pasodariya** [AAndharia/iManager#107]

**Comment by AAndharia** [comment]
Please implement this in all CRUD pages. provide me list of pages you have finished here in comment at end.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
Read task comment i've given above again and act accordingly.

**Comment by pasodariya** [comment]
### List of completed CRUD Pages which is implement this task.
* Company 
* Department
* Employee Designation
* Holiday
* Task Severity
* Task Status
* Task Types

**Comment by jmervana** [comment]
@pasodariya 
see screenshot - http://screencast.com/t/nt7OrSlxXv

**Comment by pasodariya** [comment]
Done Please verify

**Comment by jmervana** [comment]
@AAndharia 
I have checked it and looks good
