### ISSUE TITLE
Allow mark-down to be validated for required

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#113]
create attributes for mde-required and mde-required-msg which can be used to validate required for mark-down.

mde-required possible values : true, false or any js variable with bool value
default error message : Please enter value for this field.

IMPORTANT : Work on this task when there is no other clean up task remains for you.

**Comment by prupapara** [comment]
@AAndharia  Done Please verify. 

@jmervana I have Implemented required validation  for mark down. Please follow this instead of manual validation.if you need more information Please visit sample page.

**Comment by jmervana** [comment]
@AAndharia 
I have applied requird markdown and works fine
