### ISSUE TITLE
Auto Focus Directive 

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#114]

**Comment by prupapara** [comment]
Done Please verify.

**Comment by AAndharia** [comment]
@prupapara - i have assigned similar task to you or pradip. Please make sure no time is spent twice doing the same thing.

**Comment by AAndharia** [comment]
@prupapara  & @pasodariya  after you finish the task, assign it to @nirupasojitra for testing.

**Comment by prupapara** [comment]
I have change custom directive, because dynamically focus is not implemented. yet I have implemented change dynamic focus.

@pasodariya I have described how to use this directive in context.
