### ISSUE TITLE
Bind "add-employee" page in top menu. 

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#119]
Bind "add-employee" page in top menu

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by prupapara** [comment]
@pasodariya  I can see the menu in admin user.but can't see for other.also I have permission for access add employees page. but not binding in a menu. Please see screen shot.http://screencast.com/t/cmtCuMa2tIY

**Comment by pasodariya** [comment]
Permission already given but not display menu

**Comment by prupapara** [comment]
Done Please verify.

**Comment by jmervana** [comment]
@AAndharia 
I have tested and works fine
