### ISSUE TITLE
Internal Email validation message is not user friendly.  

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#120]
Internal Email validation message is not user friendly.  Please see the screen shot.
http://screencast.com/t/xTQQi3zRSMS

**Comment by AAndharia** [comment]
put @server1.com (whatever value set in web.config) outside textbox. user will just enter the email without domain. Your validations will also need to be changed.

**Comment by pasodariya** [comment]
now implement this task as per the new requirement 
please check and verify.

**Comment by prupapara** [comment]
Message is not user friendly. now message is "Email already exist. Please try different email." this message should be like this.
"This Email is already resolved. Please try different email."

**Comment by prupapara** [comment]
Verified.
