### ISSUE TITLE
Wrong message email is available when user entered internal email  

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#121]
http://localhost:52275/#/app/employees/add-employee   

Don't required this message if email is available.
now it is implemented so no problem but message should be like this "pankaj.rupapara@server1.com email is available" 

http://screencast.com/t/MYsYlIfLOSe

**Comment by AAndharia** [comment]
Remove this implementation, show error message only when email address is duplicate.

**Comment by pasodariya** [comment]
Now implemented as a new requirement
 Please check and verify

**Comment by prupapara** [comment]
As per new  verified this issue is auto fixed.
