### ISSUE TITLE
Error in Generate Employee code.

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#123]
http://localhost:52275/#/app/employees/add-employee
Error in Generate Employee code.
Please follow this video to reproduce. http://screencast.com/t/KXi2lU9o

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by prupapara** [comment]
When user is  select "--Please Select --" option still fill employee code.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by prupapara** [comment]
This is part is removed from client side.
