### ISSUE TITLE
Following employee activation format is not good.

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#124]
Following employee activation format is not good.

Hi ds dsds,
Welcome to Ingenious infoTech family.

You have to activate your account to access our website. Click on following link to activate your account.
http://localhost:52275#/app/employees/account-activation?actKey=918f8ebc-39c2-49df-ba8c-6c7d003c049c

After activation click here to login using following credentials. You’ll have to change your password on first login. Save it securely & don’t share with anyone. 

Email : pankaj.rupapara.dev@server1.com
Password : t3rdz2a5

Thank you,
pankaj rupapara.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by prupapara** [comment]
This is not part of initial requirement.
We should give Employee Code in email.
