### ISSUE TITLE
Add related(common) permission when create new employee.

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#125]
Add related(conman) permission when create new employee. Now user login then redirect  to unauthorized page.

**Comment by AAndharia** [comment]
@prupapara - please take care of this yourself. Also any other redirection for entire activation process that restricts user to go to any other pages.

**Comment by AAndharia** [comment]
Please test if anything is not remaining close it. If anything is pending, and need my input discuss with me.

**Comment by prupapara** [comment]
Verified.
