### ISSUE TITLE
Add employee  some small issue.

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#126]
http://localhost:52275/#/app/employees/add-employee
1. Secondary Phone spelling miss take
2. Change previous button text "Prev" to "Previous".
3. Change validation message on"Commitment to stay" control.
4. "Experience At joining" month validation is not working.
5 "Commitment to stay" default value 0
6. Not able to insert decimal in "Fix Pay" and "Variable Pay".
7. Arrive cursor on breadcrumbs steps NO look like link.

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by prupapara** [comment]
6. this is now working.by miss take I have created new task #149 
7. Mouse cursor should arrow.

**Comment by prupapara** [comment]
Verified.
