### ISSUE TITLE
solution directory and file structure is not proper

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#129]
Solution directory and file structure is not proper.Please see this screen shot.

http://screencast.com/t/YZIJSAwdjNLs

Also file name is not good just like one "employee-mgmt/add-employee.html"  it should name  like "employee-mgmt/add.html".

**Comment by pasodariya** [comment]
File Location are change discuss with pankaj
Please check and verify.

**Comment by prupapara** [comment]
Verified.
