### ISSUE TITLE
Bootstrap  Girding System

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#130]
Bootstrap  Girding System is not Implemented properly as per our discussion. 
just like. 
1. col-xx-x must be in "row" or "from-group"
2. we should not use any other class with girding system classes like "col-xx-x","row" or "form-group" 

This issue is in all html pages under employee-management module. Please follow proper girding system as per our session discussion.

**Comment by AAndharia** [comment]
Twitter Bootstrap Rules
===================
1. Content will always placed inside a column
2. Column will always placed inside a row
3. Row will always placed inside container or container-fluid
4. 1 Row = 12 Column. 
5. If 1 Row has more than 12 column, then any excess column group will shift to new row. 
6. each col class will give same size to higher screen if higher screen class is not specified
means if i give col-sm-6 to a div then on Medium and Large screens also it would style same as col-md-6 and col-lg-6 respecitively.
7. always use col class for lowest device you want to support. i.e. if you want to support mobile devices too then always style using col-xs. Then if you want to change any styling for any specific higher resolution device, then apply specific class for that device.
8. if you want to devide a column into more sections, again use row and then it would again become 12-col row, which you can devide again using col classes

**Comment by pasodariya** [comment]
Done Please verify

**Comment by prupapara** [comment]
Verified.
