### ISSUE TITLE
add-employee.js

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#131]
1. Please remove unused code I have seen "$scope.AddLoginInfo()"  and " $scope.AddPersonalInfo()" both function are never call.
2. Please try to reduce Jquery code in activeStateChange() function.
3. IsEmailExist() in this function few lines are actual mining less Please clean up and do simple.
4. $q is actual use fro x-editable in this page we are not used it.so Please remove $q from  dependency.
5. Please don't do any code before page is valid. because maybe it will throw error when from is invalid .

**Comment by prupapara** [comment]
This is time zone testing.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by prupapara** [comment]
Verified.
