### ISSUE TITLE
add-former-employment.js

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#132]
1. Crated Blank object  $scope.Employee = {};
2. create one  conman function for open datepicker popup.
3. Remove unused code in  "UpdateEmpFormerDetail()"   function.

Like 
                $scope.Employee.Id = data.Response.Id;
                $scope.Employee.EmployerName = data.Response.EmployerName;
                $scope.Employee.TotalEmployees = data.Response.TotalEmployees;
                $scope.Employee.Designation = data.Response.Designation;
                $scope.Employee.CTC = data.Response.CTC;
                $scope.Employee.ReasonOfLeaving = data.Response.ReasonOfLeaving;
                $scope.Employee.JoiningDate = data.Response.JoiningDate;
                $scope.Employee.RelievingDate = data.Response.RelievingDate;

Intend of 
                $scope.Employee = data.Response;

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by prupapara** [comment]
Verified.
