### ISSUE TITLE
Selected Date is not displaying in PickerDate 

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#134]
Please see this screen shot.
http://screencast.com/t/TFlUWGvf5kX

@AAndharia  We want to do create new  css class in less file for fix this UI issue.

**Comment by AAndharia** [comment]
inside theme1 folder create date-picker.less and do your css styling there.

**Comment by prupapara** [comment]
@AAndharia  Done Please verify.

**Comment by jmervana** [comment]
@AAndharia 
I have tested it and its working fine
