### ISSUE TITLE
BackEnd Code Review

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#136]
1.  api/employees/search => 
a. Change init page size. (this is not implemented by pradip)

2. api/employees/IsExistEmail   => 
a. in this action method and service some code are not necessary.
b. Please remove try cash block. 
c. Please create property in AppSettings class which is already added class in solution  for reading a "app setting" from web.config. 
d. action method rout name is not well
e. Calculate "CTC" , "Fix Pay", "Variable Pay" and varify once.
f. GetCompanyById  this method should be in companyService.cs

**Comment by pasodariya** [comment]
b. Please remove try cash block. 
this task is need to try catch block because duplication message show in front end.

**Comment by pasodariya** [comment]
Done please verify
