### ISSUE TITLE
Please use Omu.ValueInjecter instead of manually set

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#137]
Please use Omu.ValueInjecter instead of manually set. 

I know all property is not inject Using Omu.ValueInjecter. in this cache we have to do Injecter then set manually

**Comment by AAndharia** [comment]
@pasodariya - for now no need to change it in any existing code. but discuss with me what you understood by this task and what is the mistake here.

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by prupapara** [comment]
Verified.
