### ISSUE TITLE
Methods Name are not mining full

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#138]
Methods Name and some rout are not mining full.

few Mining less rout name 
1   IsExistEmail
2. GetEmpFormerDetail
3. RemoveEmpFormerDetail

few Mining less method name  
1. EmailExist
2. AccountActivation
3. RemoveEmpFormerDetail

**Comment by pasodariya** [comment]
Done Please verify

**Comment by prupapara** [comment]
Now you are calling ResetPassword method  from EmployeeMgmtService.
@pasodariya  we can call directly other service method  from controller.

**Comment by prupapara** [comment]
Everything is fine. except "ResetPassword".

**Comment by AAndharia** [comment]
Please make necessary changes and close the issue after testing.
