### ISSUE TITLE
Error when save "employee personal info"

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#154]
"Object reference not set to an instance of an object." Error throws when save "employee personal info"   step-2 (personal info).  Please see this screen shot   http://screencast.com/t/BMjefmxBve

regarding  reproduce this error.
when check same as permanent ? checkbox is check.
need more refrance Please see this screen shot
![image](https://cloud.githubusercontent.com/assets/7599647/6917081/0012c802-d7bf-11e4-9c74-cf59a765c3f0.png)

**Comment by pasodariya** [comment]
Already Done by @prupapara

**Comment by jmervana** [comment]
@AAndharia 
I have tested it
