### ISSUE TITLE
Change Task Type

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#16]
## Dev Specifications
Please specify "Dev Specifications" here and assign back to me, once i approve then only start development.

## Implementation
1. User will go to Task Detail page
1. On Task Detail page, user will be able to click on cog dropdown next to task type, and it will show all task type from which user can choose one.

## Permissions
1. Only System Analyst, Delivery Manager or Project leader can do this

## Log Activity
1. TaskId - Id Of Task
1. CreatedOn : date & time of activity
1. CreatedBy : logged in user id
1. TaskActivityType: TypeChanged (enum)
1. OldValue - old task type id
1. NewValue - new task type id

## Activity Message
* Type changed from {{previous task type}} to {{current task type}} by {createdby} {just now or before minutes, hours,days}
* Message will be generated in code not saved anywhere in database

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by prupapara** [comment]
Message is not Displaying as per Above message format.

**Comment by jmervana** [comment]
@prupapara 
Message format for all activities are changed which me and amit sir already discussed.

**Comment by prupapara** [comment]
## Permissions

Permissions is not Implanted using ng-if now it is implanted using ng-show/Hide.    

Angularjs ng-show is add ng-hide css class in element. user can change it from Dom and access everything. Please see  video. http://screencast.com/t/QePgPaNW

**Comment by jmervana** [comment]
@prupapara 
we used ng-show & ng-hide everywhere in any page

**Comment by prupapara** [comment]
Verified. except permission. I have created one new issue for permission #176

**Comment by prupapara** [comment]
Imanager task no #38
