### ISSUE TITLE
Employee-activation - step 2 - Got an error

### ISSUE THREAD

**Issue by jmervana** [AAndharia/iManager#165]
see screenshot : http://screencast.com/t/AvsEIPp0
I have clicked on next after fill data as you can see in screenshot
I got an error
see screenshot : http://screencast.com/t/HvAS2eNCOA

**Comment by prupapara** [comment]
@jmervana  Please take latest it it already fixed.
I have changed all code.

**Comment by jmervana** [comment]
sorry , I have assigned this task in another task also
@AAndharia 
I have tested this task and now its working fine
