### ISSUE TITLE
Create new task - textbox is green but error message also showing please enter data

### ISSUE THREAD

**Issue by jmervana** [AAndharia/iManager#166]
see - screenshot : http://screencast.com/t/QE4cHoD0ye

**Comment by jmervana** [comment]
@prupapara 
would you please Check again with responsibility other than Developer

**Comment by prupapara** [comment]
I have tried to fixed it, but this error in custom directive. it is some time taking. I will to it soon.

**Comment by prupapara** [comment]
Done Please verify.
Note:-Browser cash clear required.

**Comment by jmervana** [comment]
I have tested this works fine
