### ISSUE TITLE
dbo.[User][Id]  Reference in dbo.[LeaveRequest] table as a foreign key? 

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#177]
dbo.[User][Id]  Reference in dbo.[LeaveRequest] table as a foreign key? 
Please see this screen shot.http://screencast.com/t/8NHq3XeXrNej

**Comment by AAndharia** [comment]
Yes, this is correct. We always refer user id as reference not employee id. In future if requirement comes, we'll think about it. but for now, we'll keep this only.

Is there anything else you wanted to pinpoint?

**Comment by prupapara** [comment]
Nope.
