### ISSUE TITLE
Make one method to update CLUsed on each and every activity on leave

### ISSUE THREAD

**Issue by jmervana** [AAndharia/iManager#183]
**activities to handle**

1. leave request apply
2. approved
3. decline
4. cancel
5. request to cancel - approve , decline
6. reapply

when above activities will be done , call that method to update CLUsed if needed.
don't update if no change in CLUsed

when this function ready  - apply it to all places where needed

**Comment by prupapara** [comment]
Requirement changed.

**Comment by AAndharia** [comment]
closing as we are already maintaining it in #249
