### ISSUE TITLE
Issue with employee 3 step mandetory signup

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#206]
i've finished step1, signout and signin, it should take me to step2, but it is taking me to dashboard

**Comment by prupapara** [comment]
@AAndharia  As per our discussion I have created  MVC filter and Implemented on UserBaseController and relevant location. Done Please verify.

Following points are covered in this task.
* Employee is not accessible any thing without fill the three steps information.
* Employee is log-out without fill these steps, and auto open remaining step on next login.
* Employee is can't accessible already setuped information.
* Hide top menu except  profile menu(log-out).

**Comment by AAndharia** [comment]
@nirupasojitra - please test & close if all is well, assign to pankaj if you find any problem.

**Comment by nirupasojitra** [comment]
Tested & Working.
