### ISSUE TITLE
Project Management > New Project > Project Cost must specify $ and Rs or other unit

### ISSUE THREAD

**Issue by pasodariya** [AAndharia/iManager#211]
![image](https://cloud.githubusercontent.com/assets/8677663/7176403/b36c4d96-e43b-11e4-9e15-e622ff584054.png)

**Comment by jmervana** [comment]
@pasodariya 
I have discussed it with @AAndharia and decided to hold it on. it will handle in future.

**Comment by AAndharia** [comment]
Closing as this will be part of another big task.
