### ISSUE TITLE
New Task create > $filter Error

### ISSUE THREAD

**Issue by pasodariya** [AAndharia/iManager#217]
![image](https://cloud.githubusercontent.com/assets/8677663/7179587/3974c4ac-e457-11e4-997a-779a06a8a6bf.png)

**Comment by jmervana** [comment]
@pasodariya 
I cannot reproduce it , I think this error comes after underlying provider error 
so the actual error is underlying provider error

**Comment by prupapara** [comment]
@pasodariya  unable to produce at my end. Please give steps for produce.

**Comment by AAndharia** [comment]
Closing as no one is able to reproduce
