### ISSUE TITLE
Create Task > date picker not display error message 

### ISSUE THREAD

**Issue by pasodariya** [AAndharia/iManager#244]
![image](https://cloud.githubusercontent.com/assets/8677663/7199935/09358eec-e516-11e4-98af-58874b3e4a6a.png)

**Comment by prupapara** [comment]
Unable to reproduce. Please give steps for reproduce.

**Comment by pasodariya** [comment]
Discuss with pankaj and  show steps produce this issue

**Comment by prupapara** [comment]
I have tried to fix this issue using ng-pattern in date-picker element/ but it's not working because some issue in  Angular-UI.
Please see this plnkr regarding this issue.   http://plnkr.co/edit/HuFMhymU1XNt8Awhqr3n?p=preview

**Comment by AAndharia** [comment]
@prupapara - let us discuss this issue.

**Comment by prupapara** [comment]
as per me and @AAndharia dissection this task as been close.
