### ISSUE TITLE
holiday/server error message for date is hidden by date picker 

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#282]
holiday/server error message for date is not hidden by date picker 
![image](https://cloud.githubusercontent.com/assets/7599647/7229824/9e0fc99e-e785-11e4-93d0-de582b9aa172.png)

**Comment by AAndharia** [comment]
@prupapara - let us discuss this issue.

**Comment by prupapara** [comment]
as per me and  @AAndharia  discussion this task has been close.
