### ISSUE TITLE
"TaskStatu" coding standard issue

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#298]

**Comment by pasodariya** [comment]
"TaskStatu" name produce to when edmx generate automatically name changed "TaskStatus" to "TaskStatu" 
I have already discuss with amit sir

**Comment by AAndharia** [comment]
@prupapara  - it is time now to fix this issue. this will require you to rename the database table. Once it is renamed, entities will be renamed automatically, then rename necessary controller, service, vm file names and variable names, class names etc.

**Comment by prupapara** [comment]
Verified.
