### ISSUE TITLE
Not display task list when logged in user Admin

### ISSUE THREAD

**Issue by pasodariya** [AAndharia/iManager#299]
When Admin login and create new task and task created successfully but not display task list when logged in user Admin

**Comment by prupapara** [comment]
this development is pending #158

**Comment by prupapara** [comment]
@pasodariya it's working fine at my end. Please give me produce steps.

**Comment by prupapara** [comment]
1. any user when opens task list, by default filter the list by "Assignee" to logged in user. show blue filter bar to clear the filter.
2. if logged in user is admin, and user is not member of that project, then by default show all the tasks, no clear filter button will be visible.
