### ISSUE TITLE
create task > Estimation and Plan hour > exception range out of bound 

### ISSUE THREAD

**Issue by pasodariya** [AAndharia/iManager#300]
Case :1 Estimation and plan field in database datatype (4,2) change the as per requirement

Case:2 Database field data type not change else put validation message

**Comment by prupapara** [comment]
@pasodariya  I have Implanted  Point No. 1, I have increase filed size of Task Table  decimal(4,2)  to decimal (5,5) because user can add 105.55 Hours.

**Comment by prupapara** [comment]
@pasodariya  Also we should check on front side. this is part of custom directive.

**Comment by pasodariya** [comment]
Estimation and plan hour field Server side validation message not display and max-length not set
