### ISSUE TITLE
Holidays > Date picker > UI issue

### ISSUE THREAD

**Issue by nirupasojitra** [AAndharia/iManager#303]
![image](https://cloud.githubusercontent.com/assets/12133112/7345209/1eae946c-ecf0-11e4-94a0-0dcc2aa075bb.png)

**Comment by pasodariya** [comment]
@nirupasojitra This issue x-editable third party tool by default and that solution remove all the button thats done please verify

**Comment by nirupasojitra** [comment]
Tested & Working.
