### ISSUE TITLE
Holidays >  AddOffSaturdaySunday  Button > Click > Error Message

### ISSUE THREAD

**Issue by nirupasojitra** [AAndharia/iManager#304]
![image](https://cloud.githubusercontent.com/assets/12133112/7345878/c88829a2-ecf6-11e4-96cf-71bcca9e29dd.png)

**Comment by prupapara** [comment]
@nirupasojitra  Done Please verify on next release.

**Comment by nirupasojitra** [comment]
Tested and Working.
