### ISSUE TITLE
permissions > Role Permissions > Select > Accountant > Sorting

### ISSUE THREAD

**Issue by nirupasojitra** [AAndharia/iManager#311]
sorting should correctly show same all page per Application.

![image](https://cloud.githubusercontent.com/assets/12133112/7348104/411e22e4-ed0c-11e4-8c84-055435f0ffd0.png)

**Comment by prupapara** [comment]
@nirupasojitra  Done please verify on next release.

**Comment by nirupasojitra** [comment]
Tested and Working.
