### ISSUE TITLE
Task Groups > Manager task groups

### ISSUE THREAD

**Issue by nirupasojitra** [AAndharia/iManager#318]
![image](https://cloud.githubusercontent.com/assets/12133112/7369083/3911a0ec-edcc-11e4-8bee-94a6a58a8f90.png)

http://node1:81/#/app/projects/1/task-groups

**Comment by prupapara** [comment]
@nirupasojitra   I have already discuss with @AAndharia  regarding this point. this is developed by @pasodariya  as per requirement.
