### ISSUE TITLE
Holiday > calendar control select current date not implement to update. 

### ISSUE THREAD

**Issue by nirupasojitra** [AAndharia/iManager#338]
![image](https://cloud.githubusercontent.com/assets/12133112/7427314/56fee2d2-eff6-11e4-81aa-af1e4c0c37ba.png)

**Comment by prupapara** [comment]
Dne please verify.exception date-picker button.

**Comment by nirupasojitra** [comment]
everything is working fine please do remaining issue.

**Comment by prupapara** [comment]
I have discuss with @AAndharia  this button UI issue is not major, and this issue is produce from x-editable (third party lib)

After all  finally this is use close.
