### ISSUE TITLE
Create Employee Table in DB

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#37]
Employee DB design

[PK]	[Id]                          BIGINT  
[FK]  [PersonId]                    BIGINT         NOT NULL,
 [FK]  [UserId]                      BIGINT         NOT NULL,
 [FK]  [CompanyId]                   BIGINT         NOT NULL,
       [EmpCode]                     NVARCHAR (10)  NOT NULL,
	[DateOfBirth]                 DATETIME       NULL,
	[PersonalEmail]               NVARCHAR (100) NULL,
[FK]   [PermanentAddressId]          BIGINT         NULL,
[FK]   [PresentAddressId]            BIGINT         NULL,
	[IsMarried]                   BIT            NULL,
	[MarriageAnniversaryDate]     DATETIME       NULL,
	[DateOfJoining]               DATETIME       NOT NULL,
	[ExperienceAtJoiningInMonths] INT            NOT NULL,
	[CTC]                         DECIMAL (8, 2) NOT NULL,
  	[Fix]                         DECIMAL (8, 2) NOT NULL,
	[Variable]                    DECIMAL (8, 2) NOT NULL,
 [FK]  [DesignationId]               BIGINT         NOT NULL,
 [FK]  [DepartmentId]                BIGINT         NOT NULL,
    	[HasPassport]                 BIT            NULL,
	[PassportNumber]              NVARCHAR (50)  NULL,
    	[PANCardNumber]               NVARCHAR (20)  NULL,
    	[CommitmentToStayInMonths]    BIGINT         NOT NULL,
    	[CommitmentToStayNote]        NVARCHAR (400) NOT NULL,
    	[ProbationPeriodInMonths]     BIGINT         NOT NULL,
    	[IsPersonInfoSetUp]           BIT            NOT NULL,
    	[IsEmploymentRecordSetUp]     BIT            NOT NULL,
    	[IsEmployeeAddressVarified]   BIT            NOT NULL,
    	[IsEmploymentRecordVarified]  BIT            NOT NULL,
[CL]                          DECIMAL (8, 2) NOT NULL,
    	[BankName]                    NVARCHAR (MAX) NULL,
    	[BankAccountNumber]           NVARCHAR (MAX) NULL,
    	[CreatedOn]                   DATETIME       NOT NULL,
    	[UpdatedOn]                   DATETIME       NOT NULL,

**Comment by prupapara** [comment]
Done.
Please verify.

**Comment by AAndharia** [comment]
verified, made some changes and closing now.
