### ISSUE TITLE
Create New Employee - Step 1 - Personal Info

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#39]
**Add-Edit Employee Step-1	"Personal Info".**
filed list 
		**Name**
			prefix drop-down  default "Mr".
			fName,mName,lName textbox  [required]
		**Phone Number**
			Primary Phone text-box control  is [required] max-length validation  
			Secondary Phone text-box (optional) validation
                
**UI look like**
![image](https://cloud.githubusercontent.com/assets/7599647/5085453/0a74aa26-6f38-11e4-8ab1-82601af37e91.png)

If any error(s) in steps so  user can't navigate to next steps

**Comment by pasodariya** [comment]
Done Please verify

**Comment by jmervana** [comment]
@pasodariya , @prupapara , cc @AAndharia 
Please give max length as specified in database.

**Comment by prupapara** [comment]
@jmervana  Already Done.

**Comment by jmervana** [comment]
@prupapara 
No it is not there
see screenshot: http://screencast.com/t/y8tsyCx6p

**Comment by prupapara** [comment]
it is there. http://screencast.com/t/1T2roDUwA

**Comment by jmervana** [comment]
@AAndharia 
I have tested and works fine
