### ISSUE TITLE
Create New Employee - Step 2 - Login Info

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#40]
**Add-Edit Employee Step-2	"Login Info".**
filed list 
		**Company Email:**: text-box control required and email validation
                                           if input email email already exist in [dbo].[User] table. then it's not valid. 
		**Role:** drop-down control is required bind from enum.  
                 
**UI look like**
![image](https://cloud.githubusercontent.com/assets/7599647/5085955/220d426a-6f3d-11e4-8367-da3e6464180e.png)

If any error(s) in this step then user can't navigate to next steps

**Comment by jmervana** [comment]
@prupapara 
Customer should not be in dropdown in add employee
see screenshot : - http://screencast.com/t/6G4lpQtG

**Comment by prupapara** [comment]
@jmervana  Done Please verify.

**Comment by jmervana** [comment]
I have tested it and works fine
