### ISSUE TITLE
Date should not be duplicate in a financial year 

### ISSUE THREAD

**Issue by jmervana** [AAndharia/iManager#50]

**Comment by AAndharia** [comment]
Fix if not already taken care. Assign back to me when done.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
Once the duplicate date error comes, even if i change date, it is not saving.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by jmervana** [comment]
if I cannot add holiday in previous year , add functionality should not be there when previous year button is selected

**Comment by pasodariya** [comment]
Done Please verify

**Comment by jmervana** [comment]
@AAndharia 
I have tested and its looks good
