### ISSUE TITLE
CRUD Permission codes

### ISSUE THREAD

**Issue by jmervana** [AAndharia/iManager#58]
Error should not be displayed at description field see att
![permission-code-error](https://cloud.githubusercontent.com/assets/7436116/5179306/8b0103ba-74a1-11e4-95d4-16e3d1a5a41d.png)
ached screenshot

**Comment by AAndharia** [comment]
fix if not already taken care.

**Comment by jmervana** [comment]
@AAndharia 

Done please verify

**Comment by AAndharia** [comment]
Verified. Closing.
