### ISSUE TITLE
All masters - default sorting is not implemented

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#73]

**Comment by AAndharia** [comment]
Verify that default sorting is implemented for all CRUD pages and inform me the list of pages you have verified and field name for each page for default sorting.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
Verify that default sorting is implemented for all CRUD pages and inform me the list of pages you have verified and field name for each page for default sorting.

**Comment by pasodariya** [comment]
#### I have verified the all CRUD Pages list of field name  and default sorting are following :
* Company , Field name : Name , Default Sorting : Asc      
* Department , Field name : Name , Default Sorting : Asc     
* Designation, Field name : Name , Default Sorting : Asc     
* Task Severity, Field name : Name , Default Sorting : Asc     
* Task Status, Field name : Name , Default Sorting : Asc     
* Task Type, Field name : Name , Default Sorting : Asc

**Comment by jmervana** [comment]
@AAndharia 
I have tested it and works fine
