### ISSUE TITLE
after Create project redirect to project dashboard

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#76]
Related to #24

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
Still not working.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify.

**Comment by AAndharia** [comment]
1. Please use $state instead of window.location.href
2. remove any commented code
3. $rootScope.Projects = data1; - what is use of this?

**Comment by jmervana** [comment]
@AAndharia 
1. $state cannot redirect up to 2nd level like if you are at app.project.create, you cannot redirect to app.manage directly.

2. Done please verify

3. this is for bind menu dropdown for project. (refresh dropdown after add new project).

**Comment by AAndharia** [comment]
1. see what is the usage of $state.transitionTo - i think using this we can achieve what is required here
2. do not use $rootScope, use rootSvc

**Comment by jmervana** [comment]
@AAndharia 

1. yes its working and have applied
2. done please verify.

**Comment by AAndharia** [comment]
Verified. Closing.
