### ISSUE TITLE
Clean Role Permission Association

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#87]
1. Review #3  again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

method 1  - to get permission list from role
service method - permissionservice.cs >> SelectPermissionsByRole

SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Description] AS [Description]
    FROM [dbo].[Permission] AS [Extent1]
    ORDER BY [Extent1].[Id] ASC

method 2 - to modify permissions for role
service method - PermissionService.cs >> AddRemovePErmissionFromRole

add - 
INSERT [dbo].[RolePermission]([RoleId], [PermissionId])
VALUES (@0, @1)

remove - 
DELETE [dbo].[RolePermission]
WHERE (([RoleId] = @0) AND ([PermissionId] = @1))

**Comment by AAndharia** [comment]
method1 - why it doesn't have any where condition or join?

**Comment by jmervana** [comment]
@AAndharia 

because we have to fetch all conditions here see screenshot

http://screencast.com/t/Httm0rOa0

**Comment by AAndharia** [comment]
I've seen the attached image, so it means you are setting value for checkbox by looping again in c# code. Its not correct, it should be done in SQL Query directly.

hint: All Permissions Left Join with Role Permission will give you all permissions with value for checkbox

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

Sql Query

SELECT 
    [Project1].[C1] AS [C1], 
    [Project1].[Description] AS [Description], 
    [Project1].[Id] AS [Id], 
    [Project1].[C2] AS [C2]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent1].[Description] AS [Description], 
        1 AS [C1], 
        CASE WHEN (([Extent2].[RoleId] IS NULL) AND ([Extent2].[PermissionId] IS NULL)) THEN cast(0 as bit) ELSE cast(1 as bit) END AS [C2]
        FROM  [dbo].[Permission] AS [Extent1]
        LEFT OUTER JOIN [dbo].[RolePermission] AS [Extent2] ON ([Extent2].[RoleId] = @p__linq__0) AND (@p__linq__0 IS NOT NULL) AND ([Extent1].[Id] = [Extent2].[PermissionId])
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC

**Comment by AAndharia** [comment]
Verified. Closing.
