### ISSUE TITLE
Clean User Permission Association

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#88]
Review #4 again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
Review & Make corrections as per #85 for this task
For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**method1 - to get user list for typehead**
**service method - LookupService.cs >> GetUserListForTypeHead**

SELECT 
    1 AS [C1], 
    [Extent2].[Id] AS [Id], 
    [Extent1].[FirstName] + N' ' + [Extent1].[LastName] AS [C2], 
     CAST( [Extent2].[Role] AS int) AS [C3]
    FROM  [dbo].[Person] AS [Extent1]
    INNER JOIN [dbo].[User] AS [Extent2] ON [Extent1].[Id] = [Extent2].[PersonId]
    WHERE ((( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__0))), LTRIM(RTRIM(LOWER([Extent1].[FirstName])))) AS int)) = 1) OR (( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__1))), LTRIM(RTRIM(LOWER([Extent1].[LastName])))) AS int)) = 1) OR (( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__2))), LTRIM(RTRIM(LOWER([Extent2].[Email])))) AS int)) = 1)) AND ( NOT ((1 =  CAST( [Extent2].[Role] AS int)) AND ( CAST( [Extent2].[Role] AS int) IS NOT NULL))) AND (1 = [Extent2].[CanLogin])


**method 2 - get permission list for selected user**
**service method - LookupService.cs >> SelectPermissionsByUser**

[Project1].[RoleId] AS [RoleId], 
    [Project1].[Description] AS [Description], 
    [Project1].[Id] AS [Id]
    FROM ( SELECT 
        [Extent1].[RoleId] AS [RoleId], 
        [Extent2].[Id] AS [Id], 
        [Extent2].[Description] AS [Description]
        FROM  [dbo].[RolePermission] AS [Extent1]
        INNER JOIN [dbo].[Permission] AS [Extent2] ON [Extent1].[PermissionId] = [Extent2].[Id]
        WHERE ([Extent1].[RoleId] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC

method 3 - modify permission for user
**service method - LookupService.cs >> AddRemoveUserPermission**

**add -**
INSERT [dbo].[UserPermission]([UserId], [PermissionId])
VALUES (@0, @1)
SELECT [Id]
FROM [dbo].[UserPermission]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()

**remove -**
DELETE [dbo].[UserPermission]
WHERE ([Id] = @0)

**Comment by AAndharia** [comment]
1. why method2 & 3 are in lookup serviece? or it is not? if not, please send correct revised query.
2. why method2 selects RoleId?

**Comment by jmervana** [comment]
@AAndharia 
1. no method 2 & 3 are in permissionservice.cs
2. because we have to fetch all permission which are in role not only those which are assigned to user.

**Comment by AAndharia** [comment]
1. send revised query.
2. then it should come in Where condition, not in Select clause.

**Comment by jmervana** [comment]
@AAndharia 

1. 
method1 - to get user list for typehead
service method - PermissionService.cs >> GetUserListForTypeHead

SELECT 
1 AS [C1], 
[Extent2].[Id] AS [Id], 
[Extent1].[FirstName] + N' ' + [Extent1].[LastName] AS [C2], 
CAST( [Extent2].[Role] AS int) AS [C3]
FROM [dbo].[Person] AS [Extent1]
INNER JOIN [dbo].[User] AS [Extent2] ON [Extent1].[Id] = [Extent2].[PersonId]
WHERE ((( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__0))), LTRIM(RTRIM(LOWER([Extent1].[FirstName])))) AS int)) = 1) OR (( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__1))), LTRIM(RTRIM(LOWER([Extent1].[LastName])))) AS int)) = 1) OR (( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__2))), LTRIM(RTRIM(LOWER([Extent2].[Email])))) AS int)) = 1)) AND ( NOT ((1 = CAST( [Extent2].[Role] AS int)) AND ( CAST( [Extent2].[Role] AS int) IS NOT NULL))) AND (1 = [Extent2].[CanLogin])

method 2 - get permission list for selected user
service method - PermissionService.cs >> SelectPermissionsByUser

[Project1].[RoleId] AS [RoleId], 
[Project1].[Description] AS [Description], 
[Project1].[Id] AS [Id]
FROM ( SELECT 
[Extent1].[RoleId] AS [RoleId], 
[Extent2].[Id] AS [Id], 
[Extent2].[Description] AS [Description]
FROM [dbo].[RolePermission] AS [Extent1]
INNER JOIN [dbo].[Permission] AS [Extent2] ON [Extent1].[PermissionId] = [Extent2].[Id]
WHERE ([Extent1].[RoleId] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)
) AS [Project1]
ORDER BY [Project1].[Id] ASC




2. Done please verify
Query for get permission for user

SELECT 
    [Extent1].[RoleId] AS [RoleId], 
    [Extent2].[Description] AS [Description], 
    [Extent2].[Id] AS [Id], 
    CASE WHEN ([Extent3].[Id] IS NULL) THEN cast(0 as bit) ELSE cast(1 as bit) END AS [C1]
    FROM   [dbo].[RolePermission] AS [Extent1]
    INNER JOIN [dbo].[Permission] AS [Extent2] ON [Extent1].[PermissionId] = [Extent2].[Id]
    LEFT OUTER JOIN [dbo].[UserPermission] AS [Extent3] ON ([Extent3].[UserId] = @p__linq__1) AND (@p__linq__1 IS NOT NULL) AND ([Extent1].[PermissionId] = [Extent3].[PermissionId])
    WHERE ([Extent1].[RoleId] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)

**Comment by AAndharia** [comment]
Verified. Closing.
