### ISSUE TITLE
Clean CRUD - Department

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#89]
Review #5 again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
Review & Make corrections as per #85 for this task
For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by pasodariya** [comment]
(1) Add
==========
 bool isDuplicate = this.DepartmentRepo.Count(m => m.Name == departmentVM.Name) > 0;
            if (isDuplicate)
                throw new DataKeyValueException(new Dictionary<string, string>() { { "Name", "Name '" + departmentVM.Name + "' already exist. Please try different name." } });

(2) Update
===========
  bool isDuplicate = this.DepartmentRepo.Count(m => m.Name == departmentVM.Name && m.Id != departmentVM.Id) > 0;
            if (isDuplicate)
                throw new DataKeyValueException(new Dictionary<string, string>() { { "Name", "Name '" + departmentVM.Name + "' already exist. Please try different name." } });

(3) List
=========
    return this.DepartmentRepo.Select<DepartmentVM>(c => new DepartmentVM
            {
                Id = c.Id,
                Name = c.Name
            }, s => s.OrderBy(f => f.Name));
        }

Done Please verify

**Comment by AAndharia** [comment]
Please put SQL Query not LINQ Query.

**Comment by AAndharia** [comment]
1. rootSvc.setPageTitle("Departments"); - this should not be part of private variables and functions

**Comment by AAndharia** [comment]
Verified. Closing.
