### ISSUE TITLE
Clean CRUD - Designation

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#90]
1. Review #6   again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by pasodariya** [comment]
(1) Add
============
{
  bool isDuplicate = this.DesignationRepo.Count(m => m.Name == designationVM.Name) > 0;
            if (isDuplicate)
                throw new DataKeyValueException(new Dictionary<string, string>() { { "Name", "Name '" + designationVM.Name + "' already exist. Please try different name." } });
}
(2) Update
=============
{
 bool isDuplicate = this.DesignationRepo.Count(m => m.Name == designationVM.Name && m.Id != designationVM.Id) > 0;
            if (isDuplicate)
                throw new DataKeyValueException(new Dictionary<string, string>() { { "Name", "Name '" + designationVM.Name + "' already exist. Please try different name." } });
}
 (3) List
==============
{
  return this.DesignationRepo.Select<DesignationVM>(c => new DesignationVM
            {
                Id = c.Id,
                Name = c.Name
            }, s => s.OrderBy(f => f.Name));
}

Done please verify

**Comment by pasodariya** [comment]
return this.DesignationRepo.Select(c => new DesignationVM
{
Id = c.Id,
Name = c.Name
}, s => s.OrderBy(f => f.Name));

Done please verify

**Comment by AAndharia** [comment]
Please put SQL Query not LINQ Query.

**Comment by AAndharia** [comment]
rootSvc.setPageTitle("Employee Designations"); is not at proper location.

**Comment by AAndharia** [comment]
Verified. Closing.
