### ISSUE TITLE
Clean CRUD - Company

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#91]
1. Review #7  again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by pasodariya** [comment]
Method : List
===========
http://localhost:52275/api/manage/company/list
SELECT 
    [Project1].[C1] AS [C1], 
    [Project1].[Id] AS [Id], 
    [Project1].[Code] AS [Code], 
    [Project1].[Address] AS [Address], 
    [Project1].[Name] AS [Name]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent1].[Name] AS [Name], 
        [Extent1].[Code] AS [Code], 
        [Extent1].[Address] AS [Address], 
        1 AS [C1]
        FROM [dbo].[Company] AS [Extent1]
    )  AS [Project1]
    ORDER BY [Project1].[Name] ASC

 Method : Add
===========
(1) http://localhost:52275/api/manage/company/add
 SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Company] AS [Extent1]
        WHERE (([Extent1].[Name] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)) OR (([Extent1].[Code] = @p__linq__1) AND (@p__linq__1 IS NOT NULL))
    )  AS [GroupBy1]

(2) INSERT [dbo].[Company]([Name], [Code], [Address], [CreatedOn], [UpdatedOn])
VALUES (@0, @1, @2, @3, @4)
SELECT [Id]
FROM [dbo].[Company]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()

 Method : Update
===========
(1) http://localhost:52275/api/manage/company/update?fieldName=Code
SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Company] AS [Extent1]
        WHERE ((([Extent1].[Name] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)) OR (([Extent1].[Code] = @p__linq__1) AND (@p__linq__1 IS NOT NULL))) AND ( NOT (([Extent1].[Id] = @p__linq__2) AND (@p__linq__2 IS NOT NULL)))
    )  AS [GroupBy1]

(2) UPDATE [dbo].[Company]
SET [Code] = @0, [UpdatedOn] = @1
WHERE ([Id] = @2)

 Method : Remove
===========
http://localhost:52275/api/manage/company/remove
DELETE [dbo].[Company]
WHERE ([Id] = @0)

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
this is not at proper place : rootSvc.setPageTitle("Companies");

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
Verified. Closing.
