### ISSUE TITLE
Clean CRUD - Task Type

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#92]
1. Review #10   again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by pasodariya** [comment]
Method : List
===========
http://localhost:52275/api/manage/tasktype/list
SELECT 
    [Project1].[C1] AS [C1], 
    [Project1].[Id] AS [Id], 
    [Project1].[Name] AS [Name]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent1].[Name] AS [Name], 
        1 AS [C1]
        FROM [dbo].[TaskType] AS [Extent1]
    )  AS [Project1]
    ORDER BY [Project1].[Name] ASC

Method : Add
===========
http://localhost:52275/api/manage/tasktype/add
(1) SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[TaskType] AS [Extent1]
        WHERE ([Extent1].[Name] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)
    )  AS [GroupBy1]

(2) INSERT [dbo].[TaskType]([Name], [CreatedOn], [UpdatedOn])
VALUES (@0, @1, @2)
SELECT [Id]
FROM [dbo].[TaskType]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()

Method : Update
===========
http://localhost:52275/api/manage/tasktype/update?fieldName=Name
(1) SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[TaskType] AS [Extent1]
        WHERE ([Extent1].[Name] = @p__linq__0) AND (@p__linq__0 IS NOT NULL) AND ( NOT ((( CAST( [Extent1].[Id] AS int) = @p__linq__1) AND ( NOT (( CAST( [Extent1].[Id] AS int) IS NULL) OR (@p__linq__1 IS NULL)))) OR (( CAST( [Extent1].[Id] AS int) IS NULL) AND (@p__linq__1 IS NULL))))
    )  AS [GroupBy1]

(2) UPDATE [dbo].[TaskType]
SET [Name] = @0, [UpdatedOn] = @1
WHERE ([Id] = @2)

Method : Remove
===========
http://localhost:52275/api/manage/tasktype/remove
DELETE [dbo].[TaskType]
WHERE ([Id] = @0)

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
1. rootSvc.setPageTitle("Task Types"); is not at proper place

**Comment by pasodariya** [comment]
Done Please verify
