### ISSUE TITLE
Clean - CRUD - Holidays

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#95]
1. Review #36   again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by pasodariya** [comment]
Method : List
================
http://localhost:52275/api/manage/holidays/search?financialYear=currentYearList
SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[Name] AS [Name], 
    [Project1].[LeaveDate] AS [LeaveDate]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent1].[Name] AS [Name], 
        [Extent1].[LeaveDate] AS [LeaveDate]
        FROM [dbo].[Holiday] AS [Extent1]
        WHERE ([Extent1].[LeaveDate] >= @p__linq__0) AND ([Extent1].[LeaveDate] <= @p__linq__1)
    )  AS [Project1]
    ORDER BY [Project1].[Name] ASC

Method : Add
================
(1) http://localhost:52275/api/manage/holidays/add
SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Holiday] AS [Extent1]
        WHERE ([Extent1].[Name] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)
    )  AS [GroupBy1]

(2) INSERT [dbo].[Holiday]([Name], [LeaveDate], [CreatedOn], [UpdatedOn])
VALUES (@0, @1, @2, @3)
SELECT [Id]
FROM [dbo].[Holiday]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()

Method : Update
================
http://localhost:52275/api/manage/holidays/update?fieldName=Name
SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Holiday] AS [Extent1]
        WHERE ([Extent1].[Name] = @p__linq__0) AND (@p__linq__0 IS NOT NULL) AND ( NOT (([Extent1].[Id] = @p__linq__1) AND (@p__linq__1 IS NOT NULL)))
    )  AS [GroupBy1]
(2)  UPDATE [dbo].[Holiday]
SET [Name] = @0, [UpdatedOn] = @1
WHERE ([Id] = @2)

Method : Remove
================
http://localhost:52275/api/manage/holidays/remove
DELETE [dbo].[Holiday]
WHERE ([Id] = @0)

method : Search
===============
http://localhost:52275/api/manage/holidays/search?financialYear=previousYearList
SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[Name] AS [Name], 
    [Project1].[LeaveDate] AS [LeaveDate]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent1].[Name] AS [Name], 
        [Extent1].[LeaveDate] AS [LeaveDate]
        FROM [dbo].[Holiday] AS [Extent1]
        WHERE ([Extent1].[LeaveDate] >= @p__linq__0) AND ([Extent1].[LeaveDate] <= @p__linq__1)
    )  AS [Project1]
    ORDER BY [Project1].[Name] ASC

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
There are still many issues in functionality, please correct them as per our discussion. Also code corrections required as per our discussion.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
There are still issues with many functionality. Please add a complete holiday list from http://www.officeholidays.com/countries/india/ and fix all issues you come across.

**Comment by AAndharia** [comment]
Closing this now as we have a lot of modifications in holidays lately.
