### ISSUE TITLE
enhancement to AuthorizeRole attribute

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#97]
Please review #25 and implement exactly 100% same as it is mentioned. I've added some more details, so make sure you understood it clearly, or discuss with me.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
Logic is verified and is implemented correctly. Few things to take care in code

1. There are too many if else, we can remove many of them
2. Many looping code can be re-used, create some private function and use them
3. for methods specify comments, so that developer who doesn't know authorization attribute can understand the flow, which event is called when and how, what it returns etc. etc.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
Verified. Closing.
