### ISSUE TITLE
Clean - My Projects

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#98]
1. Review #19   again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task - it is for masters, but many things will be applicable to this page as well.
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

Method1 - to fetch my projects
SELECT 
    1 AS [C1], 
    [Extent2].[Id] AS [Id], 
    [Extent2].[ProjectCode] AS [ProjectCode], 
    [Extent2].[Title] AS [Title], 
    [Extent1].[ResponsibilityId] AS [ResponsibilityId], 
    [Extent1].[IsActive] AS [IsActive]
    FROM  [dbo].[ProjectMembership] AS [Extent1]
    INNER JOIN [dbo].[Project] AS [Extent2] ON [Extent1].[ProjectId] = [Extent2].[Id]
    WHERE ([Extent1].[UserId] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)

**Comment by AAndharia** [comment]
1. This is not followed - Project Status : Open, Closed, All (do not write label filters)
2. Keep space for this - title+box 
In the right side section show recent 20 task activities of all the open projects of logged in user - order by created on descending
3. please check usage of form-group and remove if not required, 
4. clean HTML as per bootstrap rules we have discussed

Note : When you post SQL Query in comment, post with Service Method Name and below it put query.

**Comment by jmervana** [comment]
@AAndharia 

1. Done please verify

2. Done please verify

3. Done please verify

4. Done please verify

**Comment by AAndharia** [comment]
Verfied. Closing.
